/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is automatically generated by Next.js and committed so clean CI and Vercel builds have the expected ambient types.
// Do not edit this file directly.
